#!/usr/bin/env python3
"""Regenerate the results table in the README and docs/results.md.

Every number published in this repository is produced here. Published ISCAS-85
redundancy figures are listed alongside as a cross-check, not as an input --
nothing in the flow consults them.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from atpg.circuit import load_bench  # noqa: E402
from atpg.flow import run_flow, verify_flow  # noqa: E402

PUBLISHED_REDUNDANT = {
    "c17": 0, "c432": 4, "c499": 8, "c880": 0, "c1355": 8, "c1908": 9,
    "c2670": 117, "c3540": 137, "c5315": 59, "c6288": 34, "c7552": 131,
}
ORDER = ["c17", "c432", "c499", "c880", "c1355", "c1908",
         "c2670", "c3540", "c5315", "c7552", "c6288"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-c6288", action="store_true",
                    help="c6288 takes several minutes; skip for a quick run")
    ap.add_argument("--random", type=int, default=2048)
    args = ap.parse_args()

    rows = []
    for name in ORDER:
        if name == "c6288" and args.skip_c6288:
            continue
        path = ROOT / "benchmarks" / f"{name}.bench"
        if not path.exists():
            print(f"skipping {name}: run scripts/fetch_benchmarks.py")
            continue
        circuit = load_bench(path)
        t0 = time.time()
        result = run_flow(circuit, n_random=args.random, backtrack_limit=50)
        ok, _ = verify_flow(circuit, result)
        rows.append((
            name, circuit.n_gates, result.n_faults, result.coverage,
            result.efficiency, len(result.patterns), len(result.redundant),
            len(result.unknown), PUBLISHED_REDUNDANT[name], time.time() - t0, ok,
        ))
        print(f"{name:8s} cov={result.coverage:7.2%} eff={result.efficiency:7.2%} "
              f"red={len(result.redundant):4d} unk={len(result.unknown):3d} "
              f"pub={PUBLISHED_REDUNDANT[name]:4d} verify={ok}")
        sys.stdout.flush()

    out = ["# Results\n",
           "Generated by `scripts/run_all.py`. Published redundancy figures are a "
           "cross-check; nothing in the flow consults them.\n",
           "| circuit | gates | faults | coverage | efficiency | patterns | "
           "redundant | unknown | published | time | verified |",
           "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        match = "✓" if r[6] + r[7] == r[8] else "✗"
        out.append(
            f"| {r[0]} | {r[1]} | {r[2]} | {r[3]:.2%} | {r[4]:.2%} | {r[5]} | "
            f"{r[6]} | {r[7]} | {r[8]} {match} | {r[9]:.1f}s | {r[10]} |"
        )
    out.append(
        "\n`unknown` faults are neither detected nor proven redundant. They are "
        "excluded from fault efficiency, because an unproven fault counted as "
        "redundant inflates the metric.\n"
    )
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "results.md").write_text("\n".join(out) + "\n")
    print(f"\nwrote {docs / 'results.md'}")
    return 0 if all(r[10] for r in rows) else 1


if __name__ == "__main__":
    sys.exit(main())
